### ISSUE TITLE
Huggingface models no longer loading correctly

### ISSUE THREAD

**Issue by ant358** [ant358/text_summariser#8]
401 Client Error: Unauthorized for url: https://huggingface.co/models/t5-large/resolve/main/config.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/transformers/configuration_utils.py", line 484, in get_config_dict
    resolved_config_file = cached_path(
  File "/usr/local/lib/python3.9/site-packages/transformers/file_utils.py", line 1271, in cached_path
    output_path = get_from_cache(
  File "/usr/local/lib/python3.9/site-packages/transformers/file_utils.py", line 1442, in get_from_cache
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/models/t5-large/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/src/main.py", line 31, in <module>
    t5_model = T5ForConditionalGeneration.from_pretrained('./models/t5-large')
  File "/usr/local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1067, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/lib/python3.9/site-packages/transformers/configuration_utils.py", line 427, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/transformers/configuration_utils.py", line 504, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for './models/t5-large'. Make sure that:

- './models/t5-large' is a correct model identifier listed on 'https://huggingface.co/models'

- or './models/t5-large' is the correct path to a directory containing a config.json file

**Comment by ant358** [comment]
sorted
